version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: devdb
    environment:
      POSTGRES_USER: userdev
      POSTGRES_PASSWORD: passworddev
      POSTGRES_DB: devdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:21.1.1
    command:
      - "start-dev"
      - "--http-port=8080"
    environment:
      # - "KEYCLOAK_IMPORT= /opt/jboss/keycloak/imports/realm-export.json"
      - "KEYCLOAK_ADMIN=keycloakdev"
      - "KEYCLOAK_ADMIN_PASSWORD=keycloakdev"
    volumes:
      - /opt/keycloak/data/import/realm-export.json
    ports:
      - "8080:8080"

volumes:
  pgdata:
