version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: devdb
    environment:
      POSTGRES_USER: userdev
      POSTGRES_PASSWORD: passworddev
      POSTGRES_DB: devdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
